### ISSUE TITLE
v3 Recode - Update tracking issue

### ISSUE THREAD

**Issue by stijnb1234** [SBDPlugins/VehiclesPlus#99]
In this issue, I will update you guys with the things I've done so far and that I want to do.

**The roadmap:**
1. Converting the basic stuff for the recode. ✅ 
2. Fixing the performance. ✅ 
3. Optimization of the API. ✅
4. Reimplementation of the front-end stuff (commands, GUIs, ...) 👷
5. Pre-beta for users on Polymart. ❌
6. Beta for all the users. ❌
7. Release. ❌

**The basic functions to reimplement:**
- [x] Basic API
- [x] Driving
- [x] Configuration (plugin itself, messages, and vehicles)
- [x] Storage -> Loading vehicles
- [x] Storage -> Saving vehicles
- [x] Commands
- [x] Inventories
- [ ] Collision and hitbox (+ slab / block driving)
- [ ] Finalize, test, and release test builds

**Current known bugs:**
- Turret does not move or shoot; no key is detected.

**_Please also see the comment below for the linked issues._**

**Comment by stijnb1234** [comment]
**Current issues to work on / things to resolve / new feature ideas:**
- [ ] Actionbar message changeable (with variables)

**Comment by stijnb1234** [comment]
**ISSUE CLOSED!**

Please move to the project board for updates.
https://github.com/SBDPlugins/VehiclesPlus/projects/1
